
export const  COUNTER_INCREMENT = "COUNTER_INCREMENT"
export const  COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const LOADING_DOCTOR="LOADING_DOCTOR"
export const ERROR_DOCTOR="ERROR_DOCTOR"


export const GET_DOCTOR="GET_DOCTOR"
export const ADD_DOCTOR="ADD_DOCTOR"
export const DELETE_DOCTOR="DELETE_DOCTOR"
export const UPDTE_DOCTOR="UPDTE_DOCTOR"
     

export const LOADING_MEDICINES="LOADING_MEDICINES"
export const ERROR_MEDICINES="ERROR_MEDICINES"


export const GET_MEDICINES="GET_MEDICINES"
export const ADD_MEDICINES="ADD_MEDICINES"
export const DELETE_MEDICINES="DELETE_MEDICINES"
export const UPDTE_MEDICINES="UPDTE_MEDICINES"


export const ADD_TO_CART ="ADD_TO_CART";
export const INC_CART ="INC_CART"
export const DEC_CART ="DEC_CART"
export const REMOVE_CART ="REMOVE_CART"

export const FAVORITE_MEDICINES ="FAVORITE_MEDICINES"
export const FAVORITE_MEDICINES_REMOVE ="FAVORITE_MEDICINES_REMOVE"

export const LOADING_DEPARTMENT="LOADING_DEPARTMENT"
export const ERROR_DEPARTMENT="ERROR_DEPARTMENT"


export const GET_DEPARTMENT="GET_DEPARTMENT"
export const ADD_DEPARTMENT="ADD_DEPARTMENT"
export const DELETE_DEPARTMENT="DELETE_DEPARTMENT"
export const UPDTE_DEPARTMENT="UPDTE_DOCTOR"


export const SIGNUP_REQEST = "SIGNUP_REQEST"
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
export const LOGIN_REQEST = "LOGIN_REQEST"
export const LOGGDE_IN = "LOGGDE_IN"
export const FORGET_REQEST = "FORGET_REQEST"
export const AUTH_ERROR ="AUTH_ERROR"
export const LOG_OUt ="LOG_OUt"
export const LOGGED_OUt ="LOGGED_OUt"
