
export const  COUNTER_INCREMENT = "COUNTER_INCREMENT"
export const  COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const GET_DOCTOR="GET_DOCTOR"
export const ADD_DOCTOR="ADD_DOCTOR"
export const DELETE_DOCTOR="DELETE_DOCTOR"
export const UPDTE_DOCTOR="UPDTE_DOCTOR"
     