
export const  COUNTER_INCREMENT = "COUNTER_INCREMENT"
export const  COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const LOADING_DOCTOR="LOADING_DOCTOR"
export const ERROR_DOCTOR="ERROR_DOCTOR"


export const GET_DOCTOR="GET_DOCTOR"
export const ADD_DOCTOR="ADD_DOCTOR"
export const DELETE_DOCTOR="DELETE_DOCTOR"
export const UPDTE_DOCTOR="UPDTE_DOCTOR"
     

export const LOADING_MEDICINES="LOADING_MEDICINES"
export const ERROR_MEDICINES="ERROR_MEDICINES"


export const GET_MEDICINES="GET_MEDICINES"
export const ADD_MEDICINES="ADD_MEDICINES"
export const DELETE_MEDICINES="DELETE_MEDICINES"
export const UPDTE_MEDICINES="UPDTE_MEDICINES"


export const ADD_TO_CART ="ADD_TO_CART";
export const INC_CART ="INC_CART"
export const DEC_CART ="DEC_CART"
export const REMOVE_CART ="REMOVE_CART"

export const FAVORITE_MEDICINES ="FAVORITE_MEDICINES"
